name: Deploy
on:
  push:
    branches:
      - main

jobs:
    docker:
        name: Docker
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
        steps:
          - uses: actions/checkout@v3
    
          - name: Setup docker buildx
            uses: docker/setup-buildx-action@v2
    
          - name: Log in to the Container registry
            uses: docker/login-action@v2
            with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}
    
          - name: Extract metadata (tags, labels) for Docker
            id: meta
            uses: docker/metadata-action@v4
            with:
              images: ghcr.io/jtheking/hackai2023athon
    
          - name: Build and push Docker image
            uses: docker/build-push-action@v4
            with:
              context: backend
              file: backend/Dockerfile
              push: true
              cache-from: type=gha
              cache-to: type=gha,mode=max
              tags: ${{ steps.meta.outputs.tags }}
              labels: ${{ steps.meta.outputs.labels }}